# Generated by Django 3.2.2 on 2021-05-18 11:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0003_groups'),
    ]

    operations = [
        migrations.AddField(
            model_name='emails',
            name='GRP_NAME',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
    ]
