# Generated by Django 3.2.2 on 2021-05-18 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0004_emails_grp_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='group_count',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('USER_ID', models.IntegerField()),
                ('GRP_COUNT', models.IntegerField()),
            ],
        ),
    ]
