# Generated by Django 3.2.2 on 2021-05-18 14:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0005_group_count'),
    ]

    operations = [
        migrations.DeleteModel(
            name='groups',
        ),
        migrations.RemoveField(
            model_name='emails',
            name='USER_ID',
        ),
        migrations.RemoveField(
            model_name='group_count',
            name='USER_ID',
        ),
        migrations.AddField(
            model_name='emails',
            name='USER_NAME',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='group_count',
            name='USER_NAME',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
    ]
