# Generated by Django 3.2.2 on 2021-05-18 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0006_auto_20210518_1944'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='emails',
            new_name='All_Emails',
        ),
        migrations.RenameModel(
            old_name='group_count',
            new_name='All_Group_count',
        ),
    ]
