# Generated by Django 3.2.2 on 2021-05-18 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0007_auto_20210518_2001'),
    ]

    operations = [
        migrations.CreateModel(
            name='Emails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('USER_NAME', models.CharField(max_length=50)),
                ('EMAIL', models.CharField(max_length=50)),
                ('GRP_ID', models.IntegerField()),
                ('GRP_NAME', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Group_count',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('USER_NAME', models.CharField(max_length=50)),
                ('GRP_COUNT', models.IntegerField()),
            ],
        ),
    ]
